CREATE TABLE Posts(
	id INT NOT NULL AUTO_INCREMENT,
	popular INT(10) DEFAULT 0,
	title VARCHAR(255) NOT NULL,
	body TEXT NOT NULL,
	category VARCHAR(100),
	author VARCHAR(100),
	site VARCHAR(100),
	text TEXT NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);